services:
  app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "5000:5000"  # WebSocket
      - "5443:5443"  # HTTPS
    volumes:
      - .:/app
      - ./data:/app/data
      - ./ssl:/app/ssl  # Mount SSL certificates
    environment:
      - DB_HOST=db
      - DB_NAME="Patient data FYP"
      - DB_USER=app_user
      - DB_PASSWORD=app_user_password
      - DB_PORT=5432
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEVICE_SECRET=${DEVICE_SECRET}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONUNBUFFERED=1
      - SSL_KEY_PATH=/app/ssl/server.key
      - SSL_CERT_PATH=/app/ssl/server.crt
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 1m
      timeout: 30s
      retries: 5
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/temp_tables.sql:/docker-entrypoint-initdb.d/02-temp-tables.sql
      - ./database/init_secure_defaults.sql:/docker-entrypoint-initdb.d/03-secure-defaults.sql
    environment:
      - POSTGRES_DB="Patient data FYP"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

volumes:
  postgres_data:
    driver: local
    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
