services:
  app:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "5000:5000"  # WebSocket
      - "5443:5443"  # HTTPS
      - "5443:5443"  # HTTPS
    volumes:
      - .:/app
      - ./data:/app/database
      - ./ssl:/app/ssl  # Mount SSL certificates
      - ./data:/app/database
      - ./ssl:/app/ssl  # Mount SSL certificates
    environment:
      - DB_HOST=db
      - DB_NAME=Patient_data_FYP
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEVICE_SECRET=${DEVICE_SECRET}
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONUNBUFFERED=1
      - SSL_KEY_PATH=/app/ssl/server.key
      - SSL_CERT_PATH=/app/ssl/server.crt
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@host.docker.internal:5432/Patient_data_FYP 
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 1m
      timeout: 30s
      retries: 5
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  db:
    build:
      context: ./database  # Path to the folder containing the Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh      
      - ./database/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/02-temp_tables.sql:/docker-entrypoint-initdb.d/02-temp-tables.sql
    environment:
      - POSTGRES_DB=Patient_data_FYP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

volumes:
  postgres_data:
    driver: local
    

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
